// <auto-generated />
using System;
using DjoppieInventory.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DjoppieInventory.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260207172900_AddAliasToAsset")]
    partial class AddAliasToAsset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("DjoppieInventory.Core.Entities.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InstallationDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDummy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficeLocation")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WarrantyExpiry")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetCode")
                        .IsUnique();

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("DjoppieInventory.Core.Entities.AssetTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InstallationDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficeLocation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WarrantyExpiry")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AssetTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetName = "Dell Latitude Laptop",
                            Brand = "Dell",
                            Building = "",
                            Category = "Computing",
                            Department = "",
                            IsActive = true,
                            Model = "Latitude 5420",
                            Owner = "",
                            TemplateName = "Dell Latitude Laptop"
                        },
                        new
                        {
                            Id = 2,
                            AssetName = "HP LaserJet Printer",
                            Brand = "HP",
                            Building = "",
                            Category = "Peripherals",
                            Department = "",
                            IsActive = true,
                            Model = "LaserJet Pro M404dn",
                            Owner = "",
                            TemplateName = "HP LaserJet Printer"
                        },
                        new
                        {
                            Id = 3,
                            AssetName = "Cisco Network Switch",
                            Brand = "Cisco",
                            Building = "",
                            Category = "Networking",
                            Department = "",
                            IsActive = true,
                            Model = "Catalyst 2960",
                            Owner = "",
                            TemplateName = "Cisco Network Switch"
                        },
                        new
                        {
                            Id = 4,
                            AssetName = "Samsung Monitor 27\"",
                            Brand = "Samsung",
                            Building = "",
                            Category = "Displays",
                            Department = "",
                            IsActive = true,
                            Model = "27\" LED Monitor",
                            Owner = "",
                            TemplateName = "Samsung Monitor 27\""
                        },
                        new
                        {
                            Id = 5,
                            AssetName = "Logitech Wireless Mouse",
                            Brand = "Logitech",
                            Building = "",
                            Category = "Peripherals",
                            Department = "",
                            IsActive = true,
                            Model = "MX Master 3",
                            Owner = "",
                            TemplateName = "Logitech Wireless Mouse"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
