// <auto-generated />
using System;
using DjoppieInventory.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DjoppieInventory.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("DjoppieInventory.Core.Entities.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("AssetTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InstallationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallationLocation")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDummy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("LegacyBuilding")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LegacyDepartment")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficeLocation")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WarrantyExpiry")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetCode")
                        .IsUnique();

                    b.HasIndex("AssetTypeId");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.HasIndex("ServiceId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("DjoppieInventory.Core.Entities.AssetEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NewValue")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PerformedByEmail")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("EventDate");

                    b.ToTable("AssetEvents");
                });

            modelBuilder.Entity("DjoppieInventory.Core.Entities.AssetTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssetName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("AssetTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InstallationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallationLocation")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LegacyBuilding")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LegacyDepartment")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficeLocation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WarrantyExpiry")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeId");

                    b.HasIndex("ServiceId");

                    b.ToTable("AssetTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetName = "Dell Latitude Laptop",
                            AssetTypeId = 1,
                            Brand = "Dell",
                            Category = "Computing",
                            IsActive = true,
                            Model = "Latitude 5420",
                            TemplateName = "Dell Latitude Laptop"
                        },
                        new
                        {
                            Id = 2,
                            AssetName = "HP LaserJet Printer",
                            AssetTypeId = 5,
                            Brand = "HP",
                            Category = "Peripherals",
                            IsActive = true,
                            Model = "LaserJet Pro M404dn",
                            TemplateName = "HP LaserJet Printer"
                        },
                        new
                        {
                            Id = 3,
                            AssetName = "Cisco Network Switch",
                            AssetTypeId = 7,
                            Brand = "Cisco",
                            Category = "Networking",
                            IsActive = true,
                            Model = "Catalyst 2960",
                            TemplateName = "Cisco Network Switch"
                        },
                        new
                        {
                            Id = 4,
                            AssetName = "Samsung Monitor 27\"",
                            AssetTypeId = 3,
                            Brand = "Samsung",
                            Category = "Displays",
                            IsActive = true,
                            Model = "27\" LED Monitor",
                            TemplateName = "Samsung Monitor 27\""
                        },
                        new
                        {
                            Id = 5,
                            AssetName = "Logitech Wireless Mouse",
                            AssetTypeId = 10,
                            Brand = "Logitech",
                            Category = "Peripherals",
                            IsActive = true,
                            Model = "MX Master 3",
                            TemplateName = "Logitech Wireless Mouse"
                        });
                });

            modelBuilder.Entity("DjoppieInventory.Core.Entities.AssetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AssetTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Code = "LAP",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Laptop",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Code = "DESK",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Desktop",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Code = "MON",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Monitor",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Code = "DOCK",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Docking Station",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Code = "KEYB",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Keyboard",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Code = "MOUSE",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Mouse",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Code = "PRN",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Printer",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Code = "NET",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Netwerk",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 5,
                            Code = "TAB",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Tablet",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 5,
                            Code = "TEL",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Telefoon",
                            SortOrder = 10
                        });
                });

            modelBuilder.Entity("DjoppieInventory.Core.Entities.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Dienst IT, Aankoopdienst, Grondgebiedzaken",
                            Code = "POORT",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Het Poortgebouw",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "Algemeen directeur, Financiën, Burgerzaken",
                            Code = "GHUIS",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Het Gemeentehuis",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Address = "Sector Mens",
                            Code = "PLAK",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "De Plak",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "WZC",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Het Woonzorgcentrum",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Code = "BKOC",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Buitenschoolse kinderopvang centrum",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 6,
                            Code = "BKOR",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Buitenschoolse kinderopvang Rooierheide",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = 7,
                            Code = "BKOL",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Buitenschoolse kinderopvang Lutselus",
                            SortOrder = 12
                        },
                        new
                        {
                            Id = 8,
                            Code = "BKOG",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Buitenschoolse kinderopvang gemeenteschool",
                            SortOrder = 13
                        },
                        new
                        {
                            Id = 9,
                            Code = "OCL",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Ontmoetingscentrum Lutselus",
                            SortOrder = 14
                        },
                        new
                        {
                            Id = 10,
                            Code = "OCR",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Ontmoetingscentrum Rooierheide",
                            SortOrder = 15
                        },
                        new
                        {
                            Id = 11,
                            Code = "GILDE",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Gildezaal",
                            SortOrder = 16
                        },
                        new
                        {
                            Id = 12,
                            Code = "KEI",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Zaal de Kei",
                            SortOrder = 17
                        },
                        new
                        {
                            Id = 13,
                            Code = "TERL",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Zaal Terloght",
                            SortOrder = 18
                        },
                        new
                        {
                            Id = 14,
                            Code = "HEIZ",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Jeugdhuis Heizoe",
                            SortOrder = 19
                        },
                        new
                        {
                            Id = 15,
                            Code = "SENH",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Seniorenhuis",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = 16,
                            Code = "ROZEN",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "School Rozendaal",
                            SortOrder = 21
                        });
                });

            modelBuilder.Entity("DjoppieInventory.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "COMP",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Computers en rekenkracht",
                            IsActive = true,
                            Name = "Computing",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "WORK",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Werkplekaccessoires en randapparatuur",
                            IsActive = true,
                            Name = "Werkplek",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "PERIPH",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Printers, scanners en andere randapparatuur",
                            IsActive = true,
                            Name = "Peripherals",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "NET",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Netwerkapparatuur",
                            IsActive = true,
                            Name = "Networking",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Code = "MOBILE",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mobiele apparaten",
                            IsActive = true,
                            Name = "Mobile",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Code = "AV",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Audio- en videoapparatuur",
                            IsActive = true,
                            Name = "Audio/Video",
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("DjoppieInventory.Core.Entities.LeaseContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContractNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MonthlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TotalValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vendor")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("EndDate");

                    b.ToTable("LeaseContracts");
                });

            modelBuilder.Entity("DjoppieInventory.Core.Entities.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Sectors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ORG",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Organisatie",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "FIN",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Financiën",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "RUI",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Ruimte",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "MENS",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Mens",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Code = "ZORG",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Zorg",
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("DjoppieInventory.Core.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SectorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("SectorId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "BSEC",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Bestuurssecretariaat",
                            SectorId = 1,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "COM",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Dienst Communicatie",
                            SectorId = 1,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "IT",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Dienst IT",
                            SectorId = 1,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "ORGB",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Dienst Organisatiebeheersing",
                            SectorId = 1,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Code = "HR",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Dienst HR",
                            SectorId = 1,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Code = "PREV",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Dienst Preventie - GIS & Noodplanning",
                            SectorId = 1,
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            Code = "AANK",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Dienst Aankopen",
                            SectorId = 2,
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            Code = "FINZ",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Dienst Financiën",
                            SectorId = 2,
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            Code = "RO",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Ruimtelijke Ontwikkeling",
                            SectorId = 3,
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 10,
                            Code = "INFRA",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Infrastructuurprojecten",
                            SectorId = 3,
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 11,
                            Code = "FAC",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Facilitaire Ondersteuning",
                            SectorId = 3,
                            SortOrder = 11
                        },
                        new
                        {
                            Id = 12,
                            Code = "OD",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Openbaar Domein",
                            SectorId = 3,
                            SortOrder = 12
                        },
                        new
                        {
                            Id = 13,
                            Code = "BB",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Beleven & Bewegen",
                            SectorId = 4,
                            SortOrder = 13
                        },
                        new
                        {
                            Id = 14,
                            Code = "BURG",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Burgerzaken",
                            SectorId = 4,
                            SortOrder = 14
                        },
                        new
                        {
                            Id = 15,
                            Code = "GO",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Gezin & Onderwijs",
                            SectorId = 4,
                            SortOrder = 15
                        },
                        new
                        {
                            Id = 16,
                            Code = "GBS",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Gemeentelijke Basisschool",
                            SectorId = 4,
                            SortOrder = 16
                        },
                        new
                        {
                            Id = 17,
                            Code = "SOC",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Sociale Dienst",
                            SectorId = 4,
                            SortOrder = 17
                        },
                        new
                        {
                            Id = 18,
                            Code = "THUIS",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Thuiszorg",
                            SectorId = 5,
                            SortOrder = 18
                        },
                        new
                        {
                            Id = 19,
                            Code = "ASWO",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Assistentiewoningen",
                            SectorId = 5,
                            SortOrder = 19
                        },
                        new
                        {
                            Id = 20,
                            Code = "CDV",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Centrum Dagverzorging",
                            SectorId = 5,
                            SortOrder = 20
                        },
                        new
                        {
                            Id = 21,
                            Code = "WZC",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Woonzorgcentrum",
                            SectorId = 5,
                            SortOrder = 21
                        });
                });

            modelBuilder.Entity("DjoppieInventory.Core.Entities.Asset", b =>
                {
                    b.HasOne("DjoppieInventory.Core.Entities.AssetType", "AssetType")
                        .WithMany("Assets")
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DjoppieInventory.Core.Entities.Service", "Service")
                        .WithMany("Assets")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssetType");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("DjoppieInventory.Core.Entities.AssetEvent", b =>
                {
                    b.HasOne("DjoppieInventory.Core.Entities.Asset", "Asset")
                        .WithMany("Events")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("DjoppieInventory.Core.Entities.AssetTemplate", b =>
                {
                    b.HasOne("DjoppieInventory.Core.Entities.AssetType", "AssetType")
                        .WithMany("Templates")
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DjoppieInventory.Core.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssetType");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("DjoppieInventory.Core.Entities.AssetType", b =>
                {
                    b.HasOne("DjoppieInventory.Core.Entities.Category", "Category")
                        .WithMany("AssetTypes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DjoppieInventory.Core.Entities.LeaseContract", b =>
                {
                    b.HasOne("DjoppieInventory.Core.Entities.Asset", "Asset")
                        .WithMany("LeaseContracts")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("DjoppieInventory.Core.Entities.Service", b =>
                {
                    b.HasOne("DjoppieInventory.Core.Entities.Sector", "Sector")
                        .WithMany("Services")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("DjoppieInventory.Core.Entities.Asset", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("LeaseContracts");
                });

            modelBuilder.Entity("DjoppieInventory.Core.Entities.AssetType", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Templates");
                });

            modelBuilder.Entity("DjoppieInventory.Core.Entities.Category", b =>
                {
                    b.Navigation("AssetTypes");
                });

            modelBuilder.Entity("DjoppieInventory.Core.Entities.Sector", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("DjoppieInventory.Core.Entities.Service", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
